# auto_build
name: auto deploy blog to ecs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: actions/ssh-client@v1
        with:
          ssh-private-key: ${{secrets.SERVER_SSH_KEY}}
          ssh-command: |
            cd /var/www/html
            git pull origin master
      - name: Restart nginx
        uses: actions/ssh-client@v1
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
          ssh-command: |
            sudo service nginx restart 
