# auto_build
name: auto deploy blog to ecs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{secrets.SERVER_SSH_KEY}}
          script: |
            cd /var/www/html
            git pull origin master
            sudo service nginx restart 
